[package]
name = "nbodysolver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
ndarray = "0.15.6"
ndarray-linalg = "0.16.0"
num-traits = "0.2.17"